### ISSUE TITLE
Z and N flags updated incorrectly after some instructions (eg. LDY)

### ISSUE THREAD

**Issue by jariseon** [naughton/mc6809#1]
thanks for the 6809 emu Patrick, i've found it very useful. to give something back, i was able to resolve a weird branching bug by replacing these js [lines](https://github.com/naughton/mc6809/blob/master/mc6809.js#L674-L685) with

```
this._flagnz = function (val) {
  _this.regCC = ((val & 0xff) == 0) ? _this.regCC |= 4 : _this.regCC &= ~4;
  _this.regCC = ((val & 0x80) != 0) ? _this.regCC |= 8 : _this.regCC &= ~8;
};
this._flagnz16 = function (val) {
  _this.regCC = ((val & 0xffff) == 0) ? _this.regCC |= 4 : _this.regCC &= ~4;
  _this.regCC = ((val & 0x8000) != 0) ? _this.regCC |= 8 : _this.regCC &= ~8;
};
```

**Comment by naughton** [comment]
i've merged your change and updated the toolchain a bit more.  still don't have defender running, but it makes it further than before thanks to your fix.
